In [2]:
import numpy as np
import pandas as pd

How likely is it that you roll doubles when rolling two dice?

In [17]:
n_trials = 100_000
n_dice = 2
dice = [1,2,3,4,5,6]
double = np.random.choice(dice, (n_trials,n_dice))
double =pd.DataFrame(double)
is_double = double.apply(lambda row: row[0] == row[1], axis=1)

In [26]:
round(len(double[is_double]) / len(double), 2)

0.17

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [37]:
n_coin = 8
coin = ['H', 'T']
coin_flip = np.random.choice(coin, (n_trials, n_coin))
coin_flip = pd.DataFrame(coin_flip)

three_heads = ((coin_flip == 'H').sum(axis=1)) == 3
len(coin_flip[three_heads])

three_or_more = coin_flip[((coin_flip == 'H').sum(axis=1)) > 3]
len(three_or_more)

63762

In [41]:
round(len(coin_flip[three_heads]) / n_trials, 2)

0.22

In [167]:
three_heads.mean()


0.2172

In [43]:
round(len(three_or_more) / n_trials, 2)

0.64

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [55]:
outcomes = ['w', 'w', 'w', 'd']
trials = 2
simulation = 100_000

billboard = np.random.choice(outcomes, (simulation,trials))
data_billboard = len(billboard[((billboard == 'd').sum(axis=1)) == 2]) 
round(data_billboard / simulation, 2)

0.06

In [171]:

(((billboard == 'd').sum(axis=1)) == 2).mean()

0.06246

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [176]:
mean = 3
std = 1.5
days = 5
stock = 17

poptarts = np.random.normal(mean, std, (simulation, days)).sum(axis=1)
available_poptarts = poptarts[np.random.normal(mean, std, (simulation, days)).sum(axis=1) < 16]

len(available_poptarts) / simulation

0.62129

Compare Heights

    Men have an average height of 178 cm and standard deviation of 8cm.
    
    Women have a mean of 170, sd = 6cm.
    
    Since you have means and standard deviations, you can use np.random.normal to generate observations.
    
    If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [83]:
men_avg = 178
men_std = 8

women_avg = 170
women_std = 6

men_height = np.random.normal(men_avg, men_std, simulation)
women_height = np.random.normal(women_avg, women_std, simulation)

women_taller = women_height > men_height
round(women_taller.mean(), 2)

0.21

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [118]:
fail = 1 / 250
students = 50

x = np.random.random((simulation, students))

In [128]:
(x  > fail).sum(axis=1)

array([49, 49, 50, ..., 50, 50, 50])

In [138]:
len(x[(x  > fail).sum(axis=1) != 50])

18379

In [136]:
1 - (len(x[(x  > fail).sum(axis=1) != 50]) / simulation)

0.81621

In [145]:
# 100 students
x_100 = np.random.random((simulation, (students * 2)))
1 - (len(x_100[(x_100  > fail).sum(axis=1) != 100]) / simulation)

0.66871

In [148]:
# prob of 150 students with a problem
x_150 = np.random.random((simulation, (students * 3)))
(len(x_150[(x_150  > fail).sum(axis=1) != 150]) / simulation)

0.45097

In [150]:
x = np.random.random((simulation, 450))
x

array([[0.42477515, 0.39571317, 0.83224456, ..., 0.39373315, 0.32929786,
        0.04205067],
       [0.1187876 , 0.25744278, 0.74939314, ..., 0.40581623, 0.26687923,
        0.91584778],
       [0.86912179, 0.68522161, 0.60508864, ..., 0.88099323, 0.71466894,
        0.60628804],
       ...,
       [0.0753595 , 0.03433014, 0.17054337, ..., 0.54753877, 0.00281245,
        0.74604418],
       [0.56948245, 0.12188018, 0.47554008, ..., 0.81137026, 0.38206976,
        0.27445349],
       [0.37173186, 0.59881275, 0.5819663 , ..., 0.90135589, 0.94725703,
        0.92119332]])

In [153]:
(x > fail).sum(axis=1)

array([False,  True, False, ..., False, False, False])

In [154]:
(x > fail).sum(axis=1) == 450

array([False,  True, False, ..., False, False, False])

In [157]:
len(x[(x > fail).sum(axis=1) == 450])

16491

In [159]:
# 450 download without a problem
(len(x[(x > fail).sum(axis=1) == 450])) / simulation

0.16491

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [202]:
truck = np.random.random((simulation,3))
yes_truck = truck < .70

In [203]:
yes_truck.sum(axis=1)

array([3, 1, 1, ..., 3, 2, 2])

In [204]:
(yes_truck.sum(axis=1) == 0).mean()

0.02777

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [207]:
n_people = 23
p  = list(range(365))

birthdays = np.random.choice(p, (simulation, n_people))

In [208]:
birthdays = pd.DataFrame(birthdays)

In [210]:
birthdays.nunique(axis=1)

0        23
1        22
2        22
3        22
4        22
         ..
99995    23
99996    23
99997    20
99998    21
99999    21
Length: 100000, dtype: int64

In [211]:
birthdays.nunique(axis=1) < n_people

0        False
1         True
2         True
3         True
4         True
         ...  
99995    False
99996    False
99997     True
99998     True
99999     True
Length: 100000, dtype: bool

In [213]:
(birthdays.nunique(axis=1) < n_people).mean()

0.50913

In [215]:
n_people = 20
(birthdays.nunique(axis=1) < n_people).mean()

0.003

In [ ]:
n_people = 40